# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v8.1.0
_src_path: gh:Tecnativa/doodba-copier-template
backup_dst: ""
cidr_whitelist: null
domains_prod: {}
domains_test: {}
gitlab_url: ""
odoo_dbfilter: ^prod
odoo_initial_lang: en_US
odoo_listdb: false
odoo_oci_image: ""
odoo_proxy: traefik
odoo_version: 17.0
paths_without_crawlers:
  - /web
  - /website/info
postgres_dbname: prod
postgres_exposed: false
postgres_username: odoo
postgres_version: "15"
project_author: Doodba-testers
project_license: BSL-1.0
project_name: doodba-test-odoo
smtp_default_from: doodba-test@example.com
smtp_relay_host: ""
traefik_version: 2
